-- 학생 테이블
CREATE TABLE TBL_STUDENT (
    STUDENT_ID NUMBER,
    NAME VARCHAR2(50),
    AGE NUMBER,
    PHONE VARCHAR2(15),
    ADDRESS VARCHAR2(100),
    CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_ID)
);

-- 과목 테이블
CREATE TABLE TBL_COURSE (
    COURSE_ID NUMBER,
    COURSE_NAME VARCHAR2(50),
    INSTRUCTOR VARCHAR2(50),
    START_DATE DATE,
    CLASS_TIME VARCHAR2(20)DEFAULT '오전 9시' NOT NULL CONSTRAINT CHECK_TIME CHECK(CLASS_TIME = '오전 9시' OR CLASS_TIME = '오후 19시'),
    CONSTRAINT PK_COURSE PRIMARY KEY(COURSE_ID)
);

-- 성적 테이블
CREATE TABLE TBL_GRADE (
    GRADE_ID NUMBER,
    STUDENT_ID NUMBER,
    COURSE_ID NUMBER,
    SCORE NUMBER,
    CONSTRAINT PK_GRADE PRIMARY KEY(GRADE_ID),
    CONSTRAINT FK_STUDENT FOREIGN KEY(STUDENT_ID) REFERENCES TBL_STUDENT(STUDENT_ID),
    CONSTRAINT FK_COURSE FOREIGN KEY(COURSE_ID) REFERENCES TBL_COURSE(COURSE_ID)
);

SELECT * FROM TBL_STUDENT;
SELECT * FROM TBL_COURSE;
SELECT * FROM TBL_GRADE;
